// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  digitalizacionSidebar: [
    'intro',
    {
      type: 'category',
      label: 'UD 1 · Mi ordenador por dentro',
      items: [{type: 'autogenerated', dirName: '01-ordenador'}],
    },
    {
      type: 'category',
      label: 'UD 2 · Mi entorno digital',
      items: [{type: 'autogenerated', dirName: '02-entorno-digital'}],
    },
    {
      type: 'category',
      label: 'UD 3 · Crea contenido',
      items: [{type: 'autogenerated', dirName: '03-contenido-digital'}],
    },
    {
      type: 'category',
      label: 'UD 4 · Seguridad en Internet',
      items: [{type: 'autogenerated', dirName: '04-seguridad'}],
    },
    {
      type: 'category',
      label: 'UD 5 · Internet y redes',
      items: [{type: 'autogenerated', dirName: '05-internet-redes'}],
    },
    {
      type: 'category',
      label: 'UD 6 · Crea tu primera app',
      items: [{type: 'autogenerated', dirName: '06-primera-app'}],
    },
  ],
};

export default sidebars;